### ISSUE TITLE
having problems with [chromex.ext.notifications]

### ISSUE THREAD

**Issue by Bigsy** [binaryage/chromex#11]
Apologies if this is me being a noob, I'm just experimenting with converting an extension and having issues calling anything in the notifications namespace from background.cljs, other `chromex.ext` commands seem to work fine eg:

```clj
(chromex.ext.context-menus/create #js {:id "wibble" :title "wibble" :contexts #js ["wibble" "wobble"]})
(chromex.ext.tabs/create #js {:url "wibble.co.uk" :pinned true})
```

But the following:
```clj
(chromex.ext.notifications/create "id" #js {:type "basic" :title "wib" :message "wib" :contextMessage "wib"}) 
```
Results in the following error (same with other notifications functions):

`Oops, Missing expected object key 'notifications' on key path 'chrome.notifications'`

**Comment by darwin** [comment]
I would guess that you forgot to add the "notifications" permission to your extension manifest.

See https://developer.chrome.com/extensions/notifications

**Comment by Bigsy** [comment]
Oh god how stupid of me, completely forgot, many thanks.
