### ISSUE TITLE
Missing a wrapper protocol for ContentSetting

### ISSUE THREAD

**Issue by isker** [binaryage/chromex#14]
Hi!  I'm trying to use chromex to use the https://developer.chrome.com/extensions/contentSettings API.  Most of the properties in that API are of type ContentSetting, which has some methods on it to alter the setting.  These methods take callback fns.

I think this type needs a wrapping protocol that produces async channels like the StorageArea and Port protocols do.  But I'm not sure :).  Let me know if I'm wrong.

Thanks!

**Comment by isker** [comment]
As a side note, the [readme](https://github.com/binaryage/chromex#flexible-marshalling) (if I'm reading it right :)) hints that this marshaling mechanism may be extended by the user:
> If you want to provide richer set of marshalling for particular APIs you care about, you [can do that consistently](https://github.com/binaryage/chromex/blob/master/src/lib/chromex/marshalling.clj).

But I can't figure out how to do that from reading that file.  Do you know of any example code for doing this?

**Comment by darwin** [comment]
You can always use javascript interop to work with those objects (using callbacks in this case).

But I agree that a wrapping similar to `StorageArea` would be convenient and consistent.

I would merge such PR. Do you want to take a stab at it?

---

Marshaling is [user-configurable](https://github.com/binaryage/chromex/blob/8ce993f6c1eaa5ed8ca4fb3f5e8f70c48da114e9/src/lib/chromex/config.clj#L20) via `:gen-marshalling` key. You can provide your own gen-marshalling and do additional marshaling there with fallback to original implementation in https://github.com/binaryage/chromex/blob/master/src/lib/chromex/marshalling.clj.

I'm not aware of any real code using that. But you can look into my tests how I implemented some trivial custom marshaling:

https://github.com/binaryage/chromex/blob/7a97f69eafd45cea1f600b1f9a93132cef357ef7/test/chromex/test_config.clj#L8
https://github.com/binaryage/chromex/blob/7a97f69eafd45cea1f600b1f9a93132cef357ef7/test/chromex/test/marshalling.clj
https://github.com/binaryage/chromex/blob/7a97f69eafd45cea1f600b1f9a93132cef357ef7/test/chromex/test/marshalling.cljs

Note that knowing config implementation I did rebind dynamic var `*gen-marshalling*` which is more dirty than providing my own config via `set-active-config!`. That is what user code should do.

**Comment by isker** [comment]
Thanks for the pointers on user-configurable marshaling.

I can try to put together a PR to add this ContentSetting marshaling.  It seems like I'd have to change a few places:
* Add new protocol to https://github.com/binaryage/chromex/blob/master/src/lib/chromex/protocols.cljs
* Add new implementation of protocol in something like https://github.com/binaryage/chromex/blob/master/src/lib/chromex/chrome_port.cljs
* Add config/defaults to https://github.com/binaryage/chromex/blob/master/src/lib/chromex/config.clj, https://github.com/binaryage/chromex/blob/master/src/lib/chromex/defaults.cljs
* Add marshaling code to https://github.com/binaryage/chromex/blob/master/src/lib/chromex/marshalling.clj and https://github.com/binaryage/chromex/blob/master/src/lib/chromex/marshalling.cljs

Does that sound right?  Am I missing anything?

**Comment by darwin** [comment]
Correct. Maybe using [`StorageArea`](https://github.com/binaryage/chromex/blob/master/src/lib/chromex/chrome_storage_area.cljs) as a template could be a bit easier. Also I think you don't have to necessary touch `config.clj` and `defaults.clj(s)`. They already refer to `marshalling.clj`.

But since you want to convert callbacks to channels, you probably want to touch them to provide user-configurable hooks similar to these:
https://github.com/binaryage/chromex/blob/master/src/lib/chromex/chrome_storage_area.cljs#L44-L45
It is not necessary, but it would be more flexible.
