### ISSUE TITLE
Setting :source-map-inline  true causes the popup to fail

### ISSUE THREAD

**Issue by rberger** [binaryage/chromex#19]
In the latest changes to example/sample/shadow, the popup fails to properly execute with the errors when `:source-map-inline  true` in `shadow-cljs.edn`:
```
Uncaught SyntaxError: Invalid or unexpected token.  shared.js:2226 
Uncaught SyntaxError: Invalid or unexpected token.  popup.js:2226 
```

2226 is. where the SHADOW_ENV.evalLoads start

Is there some other step I need to do to get this to work?

## Previous version worked other than warnings in the popup inspect console

If `:source-map-inline  false` or when running the previous git version (b9206aff8187f58a36d18a23341c4d407d7e1392)
I get a spew of warnings like the following but the popup and everything else works:

```
popup.js:2220 failed to load goog.debug.error.js Error: Namespace "goog.debug.Error" already declared.
    at Object.goog.provide (popup.js:108)
    at eval (VM851 goog.debug.error.js:1)
    at eval (<anonymous>)
    at Object.goog.globalEval (popup.js:836)
    at Object.env.evalLoad (popup.js:2218)
    at popup.js:2226
env.evalLoad @ popup.js:2220
popup.js:2220 failed to load goog.dom.nodetype.js Error: Namespace "goog.dom.NodeType" already declared.
    at Object.goog.provide (popup.js:108)
    at eval (out/cljs-runtime/goog.dom.nodetype.js:1)
    at eval (<anonymous>)
    at Object.goog.globalEval (popup.js:836)
    at Object.env.evalLoad (popup.js:2218)
    at popup.js:2227
```

**Comment by darwin** [comment]
I don't know. I probably missed this when I did my testing.

Won't have time to look into this until Saturday. You can revert the commit in the meantime. Or PRs with a fix welcome.

**Comment by rberger** [comment]
Its usable by setting `:source-map-inline false`. So I am not blocked.

I suspect fixing this problem is way beyond my current abilities, but if I discover anything will let you know or generate a PR.

Thanks again for all your help.

**Comment by darwin** [comment]
Just opened an issue upstream: https://github.com/thheller/shadow-cljs/issues/656

**Comment by darwin** [comment]
reopening because warnings in the popup module are a separate issue tracked here:
https://github.com/thheller/shadow-cljs/issues/657
