### ISSUE TITLE
slow down when using chromex.ext.downloads/tap-all-events

### ISSUE THREAD

**Issue by chrm** [binaryage/chromex#7]
I have two extensions. A regular Javascript extension and the chromex-sample extension. The only significant thing I added to the chromex-sample is `(downloads/tap-all-events chrome-event-channel)`.

I do the following command on the backgroundpage console in both extensions: `chrome.downloads.download({url: "http://example.org", filename: "example.html"})`

In the regular Javascript extensions the download finishes immediately. In the chromex-sample extension the download needs several seconds to finish.

**Comment by darwin** [comment]
No clue why this should be happening. 

If you want me to look into it, it would be great if you could share your chromex-sample fork.

**Comment by chrm** [comment]
[chromex-sample.zip](https://github.com/binaryage/chromex/files/1396465/chromex-sample.zip)

It happens in both dev and release. The slow down even affects the Javascript extension somehow if both extensions are active.

**Comment by darwin** [comment]
The problem is that you don't properly respond to `onDeterminingFilename`:
https://developer.chrome.com/extensions/downloads#event-onDeterminingFilename
